#!/bin/sh
set -e
set -u

# アプリケーションのルートディレクトリを指定
APPLICATION_ROOT="$HOME/nikocal"

# オプション設定
# 下記はデフォルトの値。変更したい場合は適宜編集
# ENVIRONMENT = test/development/production のいずれか。
PORT="3001"
BINDING_IP="172.24.212.83"
ENVIRONMENT="development"

start () {
  cd ${APPLICATION_ROOT}
  rails server --daemon --binding=${BINDING_IP} --port=${PORT} --environment=${ENVIRONMENT}
}

stop () {
  cat ${APPLICATION_ROOT}/tmp/pids/server.pid | xargs kill -9
}

restart () {
  stop
  start
}

status () {
# プロセスを表示。起動していなければ表示なし
# ちょっと手抜き実装。
  ps aux | grep "[r]ails server"
}

help () {
  echo "Usage: $0 {start|stop|restart|status|help}"
}

# 引数のサイズをチェック
# set -u と $1を併用するためのhack
# http://tech.lampetty.net/tech/index.php/archives/455
if [ $# -lt 1 ]; then
help
exit 1
fi

case "$1" in
start)
start
;;
stop)
stop
;;
restart)
restart
;;
status)
status
;;
help)
help
;;
*)
help
exit 1
esac

exit $?
